defaults:
    - agent: mpc
name: "default"
env_config_file: "config/envs/barl-cartpole.yaml"
exploration: optimistic
seed: 0
train_episodes: 250
test_episodes: 10
num_threads: 1
render: false
beta: 1.
hydra:
  run:
    dir: experiments/${name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: experiments/${name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: seed_${hydra.job.num}
